### ISSUE TITLE
guide repo name

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud-samples/traveler#1]
guide seems pretty generic when it's specifically about circuit breaker.

**Comment by fifthposition** [comment]
Hmm... I guess I wasn't thinking of naming it as relating to the service (I was thinking of e.g. the fortune-teller repo). Happy to accept suggestions for a better name though. :)

**Comment by spencergibb** [comment]
That's funny, that one of your nouns in the app is 'guide'.

**Comment by fifthposition** [comment]
Yeah—clearly more thought is not something which it would necessarily be destructive for me to put into that (or into names). Thanks.

I changed the name. Better? :smiley:

**Comment by spencergibb** [comment]
@fifthposition :+1:
